name: drag-legends
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - qgrid 
  - pandas-datareader>=0.5.0
  - matplotlib>=2.1.1
  - seaborn
  - statsmodels
  - regex
  - pip:
    - matplotlib_venn
